Update patch set 1
Patch Set 1: Verified-1

Opps, verified, that with this change the plugin size is sane: 130KB, but the tests are failing to build. Apparently I have chosen a wrong base for stable-3.1 branch?

  BUILD:80:12: Building plugins/find-owners/findowners_IT_tests.jar (8 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
plugins/find-owners/src/test/java/com/googlesource/gerrit/plugins/findowners/ApiIT.java:150: warning: non-varargs call of varargs method with inexact argument type for last parameter;
      accountCreator.create(users[i], emails1[i], "FullName " + users[i], null).id();
                                                                          ^
  cast to String for a varargs call
  cast to String[] for a non-varargs call and to suppress this warning
plugins/find-owners/src/test/java/com/googlesource/gerrit/plugins/findowners/OwnersValidatorIT.java:86: error: constructor Emails in class Emails cannot be applied to given types;
      super(null, null);
      ^
  required: ExternalIds,Provider<InternalAccountQuery>,RetryHelper
  found: <null>,<null>
  reason: actual and formal argument lists differ in length

Patch-set: 1
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1